void _putchar(char);
void _puts_recursion(char *);
void _print_rev_recursion(char *);
int _strlen_recursion(char *);
int factorial(int);
int _pow_recursion(int, int);
int _sqr_recursion(int);
int sq(int, int);
int prime(int, int);
int is_prime_number(int);
int pal(char *, int, int);
int is_palindrome(char *);
int wildcmp(char *, char *);
